services:
  fileservice.web:
    image: ${DOCKER_REGISTRY-}fileserviceweb
    build:
      context: .
      dockerfile: FileService.Web/Dockerfile
  seq:
    image: datalust/seq:latest
    container_name: seq
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_NOAUTHENTICATION=true
    ports:
      - 5341:5341
      - 8081:80
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: FileSer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Servise5
    ports:
      - "1346:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data


volumes:
  postgres-data: